fixing compiler errors with gcc 4.7 in serializer.hh
- fixes the following error:
In file included from /home/hperrey/src/eudaq/./main/include/eudaq/Event.hh:11:0,
                 from /home/hperrey/src/eudaq/./main/include/eudaq/TLUEvent.hh:5,
                 from /home/hperrey/src/eudaq/main/lib/src/TLUEvent.cc:1:
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh: In instantiation of ‘void eudaq::Serializer::write(const T&) [with T = long long unsigned int]’:
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:134:9:   required from ‘void eudaq::Serializer::write(const std::vector<T>&) [with T = long long unsigned int]’
/home/hperrey/src/eudaq/main/lib/src/TLUEvent.cc:24:27:   required from here
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:105:7: error: call of overloaded ‘GetFunc(long long unsigned int*)’ is ambiguous
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:105:7: note: candidates are:
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:60:21: note: static void (* eudaq::WriteHelper<T>::GetFunc(uint64_t*))(eudaq::Serializer&, const T&) [with T = long long unsigned int; eudaq::WriteHelper<T>::writer = void (*)(eudaq::Serializer&, const long long unsigned int&); uint64_t = long unsigned int] <near match>
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:60:21: note:   no known conversion for argument 1 from ‘long long unsigned int*’ to ‘uint64_t* {aka long unsigned int*}’
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:61:21: note: static void (* eudaq::WriteHelper<T>::GetFunc(int64_t*))(eudaq::Serializer&, const T&) [with T = long long unsigned int; eudaq::WriteHelper<T>::writer = void (*)(eudaq::Serializer&, const long long unsigned int&); int64_t = long int] <near match>
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:61:21: note:   no known conversion for argument 1 from ‘long long unsigned int*’ to ‘int64_t* {aka long int*}’
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh: In instantiation of ‘void eudaq::Deserializer::read(T&) [with T = long long unsigned int]’:
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:187:11:   required from ‘T eudaq::Deserializer::read() [with T = long long unsigned int]’
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:290:9:   required from ‘void eudaq::Deserializer::read(std::vector<T>&) [with T = long long unsigned int]’
/home/hperrey/src/eudaq/main/lib/src/TLUEvent.cc:12:25:   required from here
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:265:7: error: call of overloaded ‘GetFunc(long long unsigned int*)’ is ambiguous
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:265:7: note: candidates are:
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:215:21: note: static T (* eudaq::ReadHelper<T>::GetFunc(uint64_t*))(eudaq::Deserializer&) [with T = long long unsigned int; eudaq::ReadHelper<T>::reader = long long unsigned int (*)(eudaq::Deserializer&); uint64_t = long unsigned int] <near match>
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:215:21: note:   no known conversion for argument 1 from ‘long long unsigned int*’ to ‘uint64_t* {aka long unsigned int*}’
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:216:21: note: static T (* eudaq::ReadHelper<T>::GetFunc(int64_t*))(eudaq::Deserializer&) [with T = long long unsigned int; eudaq::ReadHelper<T>::reader = long long unsigned int (*)(eudaq::Deserializer&); int64_t = long int] <near match>
/home/hperrey/src/eudaq/./main/include/eudaq/Serializer.hh:216:21: note:   no known conversion for argument 1 from ‘long long unsigned int*’ to ‘int64_t* {aka long int*}’
make[2]: *** [main/lib/CMakeFiles/EUDAQ.dir/src/TLUEvent.cc.o] Error 1
make[1]: *** [main/lib/CMakeFiles/EUDAQ.dir/all] Error 2
make: *** [all] Error 2