serialize method for vector of bools added
not very well understood fix for this error message for MacOS Mavericks:

cd /Users/behrens/git/eudaq_aida_packet/main/lib && /usr/bin/c++
-DCPP11=1 -DEUDAQ_EXPORTS -DEUDAQ_FUNC=__func__
-DEUDAQ_PLATFORM=PF_MACOSX -std=c++11 -stdlib=libc++ -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
-fPIC -I/Users/behrens/git/eudaq_aida_packet
-I/Users/behrens/git/eudaq/./main/include    -o
CMakeFiles/EUDAQ.dir/src/StringEvent.cc.o -c
/Users/behrens/git/eudaq/main/lib/src/StringEvent.cc
In file included from
/Users/behrens/git/eudaq/./main/include/eudaq/Event.hh:11:
/Users/behrens/git/eudaq/./main/include/eudaq/Serializer.hh:105:23:
error: no matching member function for call to 'GetFunc'
      WriteHelper<T>::GetFunc(static_cast<T*>(0))(*this, v);
      ~~~~~~~~~~~~~~~~^~~~~~~
/Users/behrens/git/eudaq/./main/include/eudaq/Serializer.hh:136:9: note:
in instantiation of function template specialization
'eudaq::Serializer::write<std::__1::__bit_const_reference<std::__1::vector<bool,
std::__1::allocator<bool> > > >' requested here
        write(t[i]);
        ^
/Users/behrens/git/eudaq/./main/include/eudaq/Serializer.hh:136:9: note:
in instantiation of function template specialization
'eudaq::Serializer::write<bool>' requested here
        write(t[i]);
        ^
/Users/behrens/git/eudaq/main/lib/src/StandardEvent.cc:43:9: note: in
instantiation of function template specialization
'eudaq::Serializer::write<std::__1::vector<bool,
std::__1::allocator<bool> > >' requested here
    ser.write(m_pivot);

(cherry picked from commit a1bbb185810457694bd07f48bc28bad1b1613c54)